security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
#            http_basic:
#                realm: "Secured Demo Area"
            form_login: ~
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/articles/create, roles: ROLE_USER }
        - { path: ^/articles/delete, roles: ROLE_USER }
        - { path: ^/articles/edit, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }

    providers:
        users:
            entity: { class: AiconoaUserBundle:User }

    encoders:
        Aiconoa\UserBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1


#security:
#    encoders:
#        Aiconoa\UserBundle\Entity\User:
#            algorithm: bcrypt
#            cost: 12
#
#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
#
#    providers:
#        administrators:
#            entity: { class: AiconoaUserBundle:User}
#
#    firewalls:
#        admin_area:
#            pattern:    ^/admin
#            http_basic: ~
#        profile_area:
#            pattern:    ^/ #^/profile
#            http_basic: ~
#
#    access_control:
#        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/profile, roles: ROLE_USER }