<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    const ENTITY_CLASS_NAME = "AppBundle\Entity\Article";
    const USER_ENTITY_CLASS_NAME = "UserBundle\Entity\User";
    
    public function findWithAuthorByOffsetAndLimit($offset = null, $limit = null) {
        $query = $this->getEntityManager()->createQuery("SELECT a, u FROM ".ArticleRepository::ENTITY_CLASS_NAME." a JOIN a.author u ORDER BY a.createdOn DESC");
        
        if($offset != null) {
            $query->setFirstResult($offset);
        }
        
        if ($limit != null) {
            $query->setMaxResults($limit);
        }
        
        return $query->getResult();
    }

    public function findByAuthor($user) {
        $query = $this->getEntityManager()->createQuery("SELECT a FROM ".ArticleRepository::ENTITY_CLASS_NAME." a WHERE a.author = :author ORDER BY a.createdOn DESC");
        $query->setParameter("author", $user);
        return $query->getResult();
    }
    
    public function count() {
        $query = $this->getEntityManager()->createQuery("SELECT COUNT(a) FROM ".ArticleRepository::ENTITY_CLASS_NAME." a");
        
        return $query->getSingleScalarResult();
    }
}